### ISSUE TITLE
gvim warning at startup

### ISSUE THREAD

**Issue by hholst80** [xolox/vim-colorscheme-switcher#7]
```
Warning: The vim-colorscheme-switcher plug-in requires the
```

And then nothing. Is this a warning from your plugin or from pathogen?

**Comment by xolox** [comment]
It's a shame that the error message is truncated (are you using a very narrow gvim window?). The error message is supposed to explain that you are missing a dependency. Please review the [installation instructions](https://github.com/xolox/vim-colorscheme-switcher/blob/master/INSTALL.md). I'm closing this issue now, but feel free to re-open the issue if you can't get things to work based on the installation instructions.
